use std::collections::HashSet;
use std::env;
use std::error::Error;
use std::fs;
use std::path::PathBuf;

fn generate_banks_registry(manifest_dir: PathBuf, out_dir: PathBuf) -> Result<(), Box<dyn Error>> {
    let csv_path = manifest_dir.join("data/fints_institutes.csv");
    println!("cargo:rerun-if-changed={}", csv_path.display());

    let bytes = fs::read(csv_path)?;
    let (decoded, _, _) = encoding_rs::WINDOWS_1252.decode(&bytes);
    let mut reader = csv::ReaderBuilder::new()
        .delimiter(b';')
        .from_reader(decoded.as_bytes());
    let mut seen = HashSet::new();
    let mut banks = Vec::new();

    for result in reader.records() {
        let record = result?;
        if record.len() < 25 {
            continue;
        }

        let blz = record.get(1).unwrap_or_default().trim();
        let bic = record.get(2).unwrap_or_default().trim();
        let name = record.get(3).unwrap_or_default().trim();
        let url = record.get(24).unwrap_or_default().trim();

        if blz.len() != 8
            || !blz.bytes().all(|byte| byte.is_ascii_digit())
            || !url.starts_with("http")
            || !seen.insert(blz.to_owned())
        {
            continue;
        }

        banks.push((
            blz.to_owned(),
            bic.to_owned(),
            name.to_owned(),
            url.to_owned(),
        ));
    }

    let mut source = String::new();
    source.push_str(&format!(r#"
// AUTO-GENERATED by build.rs; do not edit by hand.
use crate::banks::BankConfig;

/// Total number of banks in the generated registry.
pub const BANK_COUNT: usize = {};

/// All known German banks with FinTS PIN/TAN access.
/// Each entry is (blz, bic, name, url).
pub static GENERATED_BANKS: &[(&str, &str, &str, &str)] = &[
"#, banks.len()
    ));

    for (blz, bic, name, url) in &banks {
        source.push_str(&format!("    ({blz:?}, {bic:?}, {name:?}, {url:?}),\n"));
    }

    source.push_str(r#"
];

/// Look up a bank by BLZ using a compile-time optimized match.
pub fn generated_bank_by_blz(blz: &str) -> Option<BankConfig> {
    let (blz, bic, name, url) = match blz {
"#);
    for (blz, bic, name, url) in &banks {
        source.push_str(&format!(
            "        {blz:?} => ({blz:?}, {bic:?}, {name:?}, {url:?}),\n"
        ));
    }
    source.push_str(r#"
        _ => return None,
    };
    Some(BankConfig::new(name, blz, bic, url))
}

/// Return all generated banks as BankConfig instances.
pub fn generated_all_banks() -> Vec<BankConfig> {
    GENERATED_BANKS
        .iter()
        .map(|(blz, bic, name, url)| BankConfig::new(*name, *blz, *bic, *url))
        .collect()
}
"#
    );

    let out_path =
        out_dir.join("banks_generated.rs");
    fs::write(out_path, source)?;

    Ok(())
}

fn main() -> Result<(), Box<dyn Error>> {
    let manifest_dir =
        PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").ok_or("missing CARGO_MANIFEST_DIR")?);
    let out_dir = PathBuf::from(env::var_os("OUT_DIR").ok_or("missing OUT_DIR")?);
    generate_banks_registry(manifest_dir, out_dir)?;

    Ok(())
}
